name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install depends with npm
        run: bun i

      - name: Emit auto import
        run: bun run test src/logic/noop.spec.ts

      - name: Typing
        run: bun run typing

      - name: Test
        run: bun run test
  release:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install depends
        run: bun i

      - name: Emit auto import
        run: bun run test src/logic/noop.spec.ts

      - name: Push to branch `release`
        run: |
          git branch release -f
          git push origin release -f

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.0.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
