name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Test
        run: |
          bun i
          bun run test
