name: TypeScript Checker Declaration

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  typing:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install depends
        run: bun i

      - name: Emit auto import
        run: bun run test src/logic/noop.spec.ts

      - name: Typing
        run: bun run typing
